ekf_filter:
    ros__parameters:
        frequency: 50.0
        sensor_timeout: 0.1
        two_d_mode: true
        
        odom0: wheel_odom
        odom0_config: [true,  true,  false,   # X, Y, Z position
                      false, false, true,    # Roll, Pitch, Yaw
                      true,  true,  false,   # X, Y, Z velocity
                      false, false, true,    # Roll, Pitch, Yaw velocity
                      false, false, false]
        odom0_queue_size: 10
        odom0_differential: false
        
        imu0: imu/data_raw
        imu0_config: [false, false, false,   # Disable orientation
                     true,  true,  true,    # Angular velocity (critical)
                     false, false, false,   # Linear acceleration
                     true,  true,  true,    # Orientation (if available)
                     false, false, false]
        imu0_queue_size: 10
        
        world_frame: odom
        odom_frame: odom
        base_link_frame: base_link
        imu0_remove_gravitational_acceleration: true