ekf_filter:
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        
        odom0: wheel_odom
        odom0_config: [true, true, false,   # X, Y position
                      false, false, true,  # Yaw orientation
                      true, true, false,   # X, Y velocity
                      false, false, true]  # Yaw rate
        odom0_differential: false
        
        imu0: imu/data_raw
        imu0_config: [true, true, true,   # Disable orientation
                     true, true, true,      # Angular velocity
                     false, false, false,   # Linear acceleration
                     false, false, false]   # Disable orientation fields
        imu0_remove_gravitational_acceleration: true
        
        world_frame: odom
        odom_frame: odom
        base_link_frame: base_link