ekf_filter:
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        publish_tf: true
        
        # Robust frame configuration
        world_frame: odom
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link

        # Sensor Input Configuration
        odom0: wheel_odom
        odom0_config: [true, true, false,   # x, y, z position
                    false, false, true,   # roll, pitch, yaw
                    true, true, false,    # vx, vy, vz
                    false, false, true,   # vroll, vpitch, vyaw
                    false, false, false]  # ax, ay, az
        odom0_differential: false
        odom0_relative: false
        odom0_queue_size: 10
        odom0_nodelay: true

        # IMU Input with more conservative settings
        imu0: imu/data_raw
        imu0_config: [false, false, false,  # x, y, z position
                    false, false, true,    # roll, pitch, yaw
                    false, false, false,   # vx, vy, vz
                    false, false, true,    # vroll, vpitch, vyaw
                    true, true, false]     # ax, ay, az
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true
        imu0_nodelay: true

