ekf_filter:
    ros__parameters:
        frequency: 20.0  # Lower frequency for stability
        two_d_mode: true
        publish_tf: true
        
        # Frame configuration
        world_frame: odom
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link

        # Odometry - primary source
        odom0: wheel_odom
        odom0_config: [true, true, false,   # x, y position
                    false, false, true,     # yaw only
                    true, true, false,      # vx, vy velocities
                    false, false, true,     # vyaw
                    false, false, false]    # no acceleration from odometry
        odom0_differential: false
        odom0_relative: false
        odom0_queue_size: 10
        odom0_nodelay: true

        # IMU - use minimally to avoid conflicts
        imu0: imu/data_raw
        imu0_config: [false, false, false,  # no position
                    false, false, false,    # no orientation - this is key!
                    false, false, false,    # no velocity
                    false, false, true,     # only use angular z velocity
                    true, true, false]      # x, y acceleration only
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true
        imu0_nodelay: true