controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    use_rotate_to_heading: true
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    controller_plugins: ["FollowPath"]

FollowPath:
  plugin: "dwb_core::DWBLocalPlanner"
  debug_trajectory_details: True
  min_vel_x: 0.0
  max_vel_x: 0.2
  min_vel_y: 0.0
  max_vel_y: 0.0
  min_rot_vel: -1.5
  max_rot_vel: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.57
  inflation_radius: 0.15

lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: ["controller_server", "planner_server", "behavior_server", "bt_navigator"]

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]

behavior_server:
  ros__parameters:
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "spin"
      spin_dist: 1.57
    backup:
      plugin: "backup"
      backup_dist: 0.15
      backup_speed: 0.025
    wait:
      plugin: "wait"
      wait_time: 5.0

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: base_link
      update_frequency: 0.5
      publish_frequency: 1.0
      width: 8  # Ensure this is an integer
      height: 8  # Ensure this is an integer
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          data_type: "LaserScan"
          topic: /scan
          marking: true
          clearing: true
        inflation_radius: 0.15

local_costmap:
  local_costmap:
    ros__parameters:
      robot_base_frame: base_link
      update_frequency: 2.0
      publish_frequency: 2.0
      width: 3  # Ensure this is an integer
      height: 3  # Ensure this is an integer
      resolution: 0.05
      plugins: ["obstacle_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          data_type: "LaserScan"
          topic: /scan
          marking: true
          clearing: true
        inflation_radius: 0.15