async_slam_toolbox:
  ros__parameters:
    scan_topic: /scan
    scan_queue_size: 30
    throttle_scans: 4  # Process every 4th scan
    transform_publish_period: 0.1
    minimum_time_interval: 0.2
    map_update_interval: 2.0
    resolution: 0.05
    max_lidar_range: 12.0  # Match your RPLIDAR specs
    minimum_lidar_range: 0.1  # Prevent invalid readings
